<?php

declare(strict_types=1);

/**
 * Central-database multi-center configuration.
 */
return [
    'central_domains' => [
        '127.0.0.1',
        'localhost',
        env('APP_DOMAIN', 'edu-center.kareemsoft.org'),
    ],

    'scoped_tables' => [
        'users',
        'teachers',
        'grades',
        'classes',
        'sections',
        'teacher_section',
        'fees',
        'payments',
        'attendances',
        'homeworks',
        'student_homework',
        'quiz_degrees',
        'exam_degrees',
        'library',
        'announcements',
        'events',
        'images',
        'parent_attachments',
        'settings',
        'whatsapp_templates',
        'certification_templates',
        'student_certifications',
        'activity_logs',
        'months',
        'genders',
        'rooms',
        'sessions',
        'notes',
        'personal_todos',
        'personal_notes',
        'units',
        'lessons',
        'questions',
        'answers',
        'words',
        'landing_pages',
        'landing_page_revisions',
        'landing_page_analytics',
        'landing_media',
        'media',
        'notifications',
        'online_classes',
        'roles',
        'permissions',
        'model_has_roles',
        'model_has_permissions',
        'role_has_permissions',
        'failed_jobs',
        'password_resets',
    ],

    /** Tables scoped by center_memberships morph (user_id + user_type). */
    'membership_scoped_tables' => [
        'students' => \App\Models\Student::class,
        'parents' => \App\Models\Parents::class,
    ],

    'global_identity' => [
        'enabled' => env('GLOBAL_IDENTITY_ENABLED', true),
        'roles' => ['parent', 'student'],
    ],

    'migration_order' => [
        'genders',
        'months',
        'settings',
        'users',
        'parents',
        'teachers',
        'grades',
        'roles',
        'permissions',
        'role_has_permissions',
        'classes',
        'sections',
        'teacher_section',
        'students',
        'parent_attachments',
        'fees',
        'payments',
        'attendances',
        'events',
        'rooms',
        'sessions',
        'online_classes',
        'homeworks',
        'student_homework',
        'units',
        'lessons',
        'questions',
        'answers',
        'words',
        'notes',
        'personal_todos',
        'personal_notes',
        'quiz_degrees',
        'exam_degrees',
        'library',
        'announcements',
        'images',
        'activity_logs',
        'whatsapp_templates',
        'certification_templates',
        'student_certifications',
        'landing_pages',
        'landing_page_revisions',
        'landing_page_analytics',
        'landing_media',
        'media',
        'notifications',
        'model_has_roles',
        'model_has_permissions',
        'failed_jobs',
        'password_resets',
    ],

    'migration_foreign_keys' => [
        'classes' => ['grade_id' => 'grades'],
        'sections' => [
            'grade_id' => 'grades',
            'class_id' => 'classes',
            'teacher_id' => 'teachers',
        ],
        'teacher_section' => [
            'teacher_id' => 'teachers',
            'section_id' => 'sections',
        ],
        'students' => [
            'grade_id' => 'grades',
            'class_id' => 'classes',
            'section_id' => 'sections',
            'parent_id' => 'parents',
        ],
        'parent_attachments' => ['parent_id' => 'parents'],
        'fees' => [
            'grade_id' => 'grades',
            'class_id' => 'classes',
            'section_id' => 'sections',
        ],
        'payments' => [
            'student_id' => 'students',
            'fee_id' => 'fees',
        ],
        'attendances' => ['student_id' => 'students'],
        'homeworks' => [
            'grade_id' => 'grades',
            'class_id' => 'classes',
            'section_id' => 'sections',
            'teacher_id' => 'teachers',
        ],
        'student_homework' => [
            'student_id' => 'students',
            'homework_id' => 'homeworks',
        ],
        'units' => [
            'grade_id' => 'grades',
            'class_id' => 'classes',
        ],
        'lessons' => ['unit_id' => 'units'],
        'questions' => ['lesson_id' => 'lessons'],
        'answers' => ['question_id' => 'questions'],
        'words' => ['lesson_id' => 'lessons'],
        'notes' => ['student_id' => 'students'],
        'quiz_degrees' => ['student_id' => 'students'],
        'exam_degrees' => ['student_id' => 'students'],
        'library' => [
            'grade_id' => 'grades',
            'class_id' => 'classes',
            'section_id' => 'sections',
        ],
        'announcements' => [
            'grade_id' => 'grades',
            'class_id' => 'classes',
            'section_id' => 'sections',
        ],
        'sessions' => [
            'grade_id' => 'grades',
            'class_id' => 'classes',
            'section_id' => 'sections',
        ],
        'online_classes' => [
            'grade_id' => 'grades',
            'class_id' => 'classes',
            'section_id' => 'sections',
        ],
        'landing_pages' => ['teacher_id' => 'teachers'],
        'student_certifications' => [
            'template_id' => 'certification_templates',
            'student_id' => 'students',
            'section_id' => 'sections',
        ],
        'landing_page_revisions' => ['landing_page_id' => 'landing_pages'],
        'landing_page_analytics' => ['landing_page_id' => 'landing_pages'],
        'model_has_roles' => ['role_id' => 'roles'],
        'model_has_permissions' => ['permission_id' => 'permissions'],
        'role_has_permissions' => [
            'role_id' => 'roles',
            'permission_id' => 'permissions',
        ],
    ],
];
