export interface WebsiteImageDefinition {
  key: string;
  name: string;
  defaultUrl: string;
  category: 'Authentication' | 'Landing page' | 'Dashboard previews' | 'Education illustrations' | 'Branding';
  pages: string[];
  recommendedWidth: number;
  recommendedHeight: number;
  fit: 'cover' | 'contain';
}

export const WEBSITE_IMAGES: WebsiteImageDefinition[] = [
  {
    key: 'tenant-login-background',
    name: 'Portal login and registration background',
    defaultUrl: '/images/tenant-login-egypt-bg.png',
    category: 'Authentication',
    pages: ['Admin login', 'Teacher login', 'Student login', 'Parent login', 'Student registration', 'Parent registration'],
    recommendedWidth: 1920,
    recommendedHeight: 1080,
    fit: 'cover',
  },
  {
    key: 'platform-contact-egypt',
    name: 'Platform contact Egypt landmark',
    defaultUrl: '/images/image_1.png',
    category: 'Landing page',
    pages: ['Platform landing page'],
    recommendedWidth: 1200,
    recommendedHeight: 800,
    fit: 'contain',
  },
  {
    key: 'landing-template-arabic-teacher',
    name: 'Arabic teacher template thumbnail',
    defaultUrl: '/images/landing-templates/arabic-teacher-premium.png',
    category: 'Landing page',
    pages: ['Landing page builder'],
    recommendedWidth: 1200,
    recommendedHeight: 675,
    fit: 'cover',
  },
  {
    key: 'admin-dashboard-preview',
    name: 'Admin dashboard preview',
    defaultUrl: '/images/admin_dashboard.png',
    category: 'Dashboard previews',
    pages: ['Platform landing page'],
    recommendedWidth: 1920,
    recommendedHeight: 1080,
    fit: 'cover',
  },
  {
    key: 'teacher-dashboard-preview',
    name: 'Teacher dashboard preview',
    defaultUrl: '/images/teacher_dashboard.png',
    category: 'Dashboard previews',
    pages: ['Platform landing page'],
    recommendedWidth: 1920,
    recommendedHeight: 1080,
    fit: 'cover',
  },
  {
    key: 'student-dashboard-preview',
    name: 'Student dashboard preview',
    defaultUrl: '/images/student_dashboard.png',
    category: 'Dashboard previews',
    pages: ['Platform landing page'],
    recommendedWidth: 1920,
    recommendedHeight: 1080,
    fit: 'cover',
  },
  {
    key: 'parent-dashboard-preview',
    name: 'Parent dashboard preview',
    defaultUrl: '/images/parent_dashboard.png',
    category: 'Dashboard previews',
    pages: ['Platform landing page'],
    recommendedWidth: 1920,
    recommendedHeight: 1080,
    fit: 'cover',
  },
  {
    key: 'legacy-student-login',
    name: 'Legacy student login illustration',
    defaultUrl: '/images/student_login.png',
    category: 'Authentication',
    pages: ['Legacy asset (currently unused)'],
    recommendedWidth: 800,
    recommendedHeight: 800,
    fit: 'contain',
  },
  {
    key: 'education-hero-classroom',
    name: 'Classroom hero illustration',
    defaultUrl: '/images/education-egypt/hero-classroom.svg',
    category: 'Education illustrations',
    pages: ['Landing and dashboard illustrations'],
    recommendedWidth: 1200,
    recommendedHeight: 800,
    fit: 'contain',
  },
  {
    key: 'education-teacher-lesson',
    name: 'Teacher lesson illustration',
    defaultUrl: '/images/education-egypt/teacher-lesson.svg',
    category: 'Education illustrations',
    pages: ['Landing and dashboard illustrations'],
    recommendedWidth: 800,
    recommendedHeight: 600,
    fit: 'contain',
  },
  {
    key: 'education-student-learning',
    name: 'Student learning illustration',
    defaultUrl: '/images/education-egypt/student-learning.svg',
    category: 'Education illustrations',
    pages: ['Landing and dashboard illustrations'],
    recommendedWidth: 800,
    recommendedHeight: 600,
    fit: 'contain',
  },
  {
    key: 'education-parent-support',
    name: 'Parent support illustration',
    defaultUrl: '/images/education-egypt/parent-support.svg',
    category: 'Education illustrations',
    pages: ['Landing and dashboard illustrations'],
    recommendedWidth: 800,
    recommendedHeight: 600,
    fit: 'contain',
  },
  {
    key: 'education-library-books',
    name: 'Library books illustration',
    defaultUrl: '/images/education-egypt/library-books.svg',
    category: 'Education illustrations',
    pages: ['Library pages'],
    recommendedWidth: 800,
    recommendedHeight: 600,
    fit: 'contain',
  },
  {
    key: 'education-center-campus',
    name: 'Education center campus illustration',
    defaultUrl: '/images/education-egypt/center-campus.svg',
    category: 'Education illustrations',
    pages: ['Landing and dashboard illustrations'],
    recommendedWidth: 1000,
    recommendedHeight: 700,
    fit: 'contain',
  },
  {
    key: 'education-exam-prep',
    name: 'Exam preparation illustration',
    defaultUrl: '/images/education-egypt/exam-prep.svg',
    category: 'Education illustrations',
    pages: ['Exam pages'],
    recommendedWidth: 800,
    recommendedHeight: 600,
    fit: 'contain',
  },
  {
    key: 'education-live-class',
    name: 'Live class illustration',
    defaultUrl: '/images/education-egypt/live-class.svg',
    category: 'Education illustrations',
    pages: ['Live session pages'],
    recommendedWidth: 800,
    recommendedHeight: 600,
    fit: 'contain',
  },
  {
    key: 'platform-promo-portrait',
    name: 'Platform promotional portrait',
    defaultUrl: '/images/ChatGPT Image Jun 17, 2026, 09_01_24 PM.png',
    category: 'Landing page',
    pages: ['Static asset (currently unused)'],
    recommendedWidth: 1024,
    recommendedHeight: 1536,
    fit: 'cover',
  },
  {
    key: 'application-icon',
    name: 'Application icon',
    defaultUrl: '/brand/app-icon.svg',
    category: 'Branding',
    pages: ['Application branding'],
    recommendedWidth: 512,
    recommendedHeight: 512,
    fit: 'contain',
  },
];

export const WEBSITE_IMAGE_BY_DEFAULT_URL = new Map(
  WEBSITE_IMAGES.map(image => [image.defaultUrl, image]),
);
