export { authApi } from './auth';
export { notificationsApi } from './notifications';
export { dashboardApi } from './dashboard';
export { platformApi } from './platform';
export { adminApi } from './admin';
export { adminStudentsApi } from './admin-students';
export { adminTeachersApi } from './admin-teachers';
export { adminParentsApi } from './admin-parents';
export { adminAcademicsApi } from './admin-academics';
export { adminAttendanceApi } from './admin-attendance';
export { adminLearningApi } from './admin-learning';
export { adminAssessmentsApi } from './admin-assessments';
export { adminFeesApi } from './admin-fees';
export { adminPaymentsApi } from './admin-payments';
export { adminAccessApi } from './admin-access';
export { adminLibraryApi } from './admin-library';
export { adminAnnouncementsApi } from './admin-announcements';
export { adminReportsApi } from './admin-reports';
export { adminSessionsApi } from './admin-sessions';
export { teacherApi } from './teacher';
export { parentApi } from './parent';
export { studentSelfApi } from './student-self';
export { teacherSessionsApi } from './teacher-sessions';
export { adminLandingApi, publicLandingApi } from './admin-landing';
export { configApi } from './config';
export type { AppConfig, TenancyMode } from './config';